apiVersion: v1
kind: Service
metadata:
  name: hello-api
  labels:
    app: hello-api
spec:
  type: ClusterIP
  selector:
    app: hello-api
  ports:
    - name: http
      port: 8000
      targetPort: http